exports.TWITTER_USER_IDS = {
	"ed sheeran": "edsheeran",
	"muse": "muse",
 	"justin bieber": "justinbieber",
	"lady gaga": "ladygaga",
	"katy perry": "katyperry",
	"rihanna": "rihanna",
	"taylor swift": "taylorswift13",
	"britney spears": "britneyspears",
	"shakira": "shakira",
	"justin timberlake": "jtimberlake",
	"jennifer lopez": "jlo",
	"nicki minaj": "nickiminaj",
	"bruno mars": "brunomars",
	"p!nk": "pink",
	"selena gomez": "selenagomez",
	"marshall mathers": "eminem",
	"demetria lovato": "ddlovato",
	"adele": "officialadele",
	"alicia keys": "aliciakeys",
	"chris brown": "chrisbrown",
	"harry styles": "harry_styles",
	"miley ray cyrus": "mileycyrus",
	"one direction": "onedirection",
	"lil wayne weezy f": "liltunechi",
	"niall horan": "niallofficial",
	"snoop dogg": "snoopdogg",
	"louis tomlinson": "louis_tomlinson",
	"mariah carey": "mariahcarey",
	"liam payne": "real_liam_payne",
	"coldplay": "coldplay",
	"wiz khalifa": "wizkhalifa",
	"pitbull": "pitbull",
	"avril lavigne": "avrillavigne",
	"ashley tisdale": "ashleytisdale",
	"kanye west": "kanyewest",
	"alejandro sanz": "alejandrosanz",
	"iamdiddy": "iamdiddy",
	"zayn malik": "zaynmalik",
	"ricky martin": "ricky_martin",
	"david guetta": "davidguetta",
	"ivete sangalo": "ivetesangalo",
	"50cent": "50cent",
	"juanes": "juanes",
	"beyoncé knowles": "beyonce",
	"ludacris": "ludacris",
	"usher": "usherraymondiv",
	"agnes monica": "agnezmo",
	"will.i.am": "iamwill",
	"paulina rubio": "paurubio",
	"jessie j": "jessiej",
	"jessica simpson": "jessicasimpson",
	"trey songz": "treysongz",
	"ed sheeran": "edsheeran",
	"nick jonas": "nickjonas",
	"carly rae jepsen": "carlyraejepsen",
	"sherina munaf": "sherinamunaf",
	"t-raww": "tyga",
	"joe jonas": "joejonas",
	"soulja boy": "souljaboy",
	"jason mraz": "jason_mraz",
	"kelly rowland": "kellyrowland",
	"david bisbal": "davidbisbal",
	"calle 13": "calle13oficial",
	"luis fonsi": "luisfonsi",
	"thalia": "thalia",
	"queen latifah": "iamqueenlatifah",
	"daddy yankee": "daddy_yankee",
	"vidi aldiano": "vidialdiano",
	"cody simpson": "codysimpson",
	"lmfao": "lmfao",
	"luan santana": "luansantana",
	"christina aguilera": "xtina",
	"cher lloyd": "cherlloyd",
	"olly murs": "ollyofficial",
	"afgansyah reza": "afgansyah_reza",
	"lenny kravitz": "lennykravitz",
	"jonas brothers": "jonasbrothers",
	"john legend": "johnlegend",
	"lily allen": "lilyrosecooper",
	"rev run": "revrunwisdom",
	"adam levine": "adamlevine",
	"sandy leah": "sandyleah",
	"mary j. blige": "maryjblige",
	"sean kingston": "seankingston",
	"jaden smith": "officialjaden",
	"big sean": "bigsean",
	"cheryl cole": "cherylcole",
	"t.i.": "tip",
	"kelly clarkson": "kelly_clarkson",
	"yoko ono": "yokoono",
	"ricardo montaner": "montanertwiter",
	"mac miller": "macmiller",
	"ll cool j": "llcoolj",
	"chayanne": "chayannemusic",
	"ne-yo":"neyocompound",
	"j. cole": "jcolenc",
	"juan luis guerra": "juanluisguerra",
	"miranda cosgrove": "mirandacosgrove",
	"enrique iglesias": "enrique305",
	"ciara": "ciara",
	"siwon choi": "siwon407",
	"ke$ha": "keshasuxx"
}